version: "3"

services:
  phoenix:
    build: .
    env_file:
      - .env.prod
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    image: postgres:10
    env_file:
      - .env.prod
